version: '3.9'

services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mydogRubi
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - training-buddy-private

volumes:
  postgres-data:

networks:
  training-buddy-private: